export const PRACTICE_PROBLEMS = [
  {
    id: 'two-sum',
    title: 'Two Sum',
    difficulty: 'Easy',
    category: 'arrays',
    prompt: 'Given an array of integers and a target, return indices of two numbers that add up to the target.',
    hint: 'Use a hash map to store values you have already seen.',
    solution: 'For each value x, check whether target - x is already in the map. If yes, return both indices; otherwise store x.',
  },
  {
    id: 'valid-parentheses',
    title: 'Valid Parentheses',
    difficulty: 'Easy',
    category: 'stack',
    prompt: 'Determine whether every opening bracket is closed by the same type of bracket in the correct order.',
    hint: 'Push opening brackets and match closing brackets against the top of the stack.',
    solution: 'Use a stack. For each closing bracket, pop and compare. At the end the stack must be empty.',
  },
  {
    id: 'number-of-islands',
    title: 'Number of Islands',
    difficulty: 'Medium',
    category: 'graph',
    prompt: 'Count connected components of land cells in a 2D grid.',
    hint: 'Run DFS or BFS from each unvisited land cell.',
    solution: 'Scan the grid. When you find unvisited land, increment count and flood-fill all connected land.',
  },
  {
    id: 'coin-change',
    title: 'Coin Change',
    difficulty: 'Medium',
    category: 'dp',
    prompt: 'Find the minimum number of coins needed to make a target amount.',
    hint: 'Let dp[x] be the fewest coins needed for amount x.',
    solution: 'Initialize dp[0]=0 and all others infinity. For every amount and coin, relax dp[amount].',
  },
  {
    id: 'n-queens-practice',
    title: 'N-Queens II',
    difficulty: 'Hard',
    category: 'backtracking',
    prompt: 'Return the number of distinct ways to place n queens on an n by n board.',
    hint: 'Track occupied columns and diagonals to prune checks in O(1).',
    solution: 'Backtrack row by row. Use sets for columns, row-col diagonals, and row+col diagonals.',
  },
];
