export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  DASHBOARD: '/dashboard',
  SORTING: '/algorithms/sorting',
  SORTING_ALGO: '/algorithms/sorting/:algorithm',
  SEARCHING: '/algorithms/searching',
  SEARCHING_ALGO: '/algorithms/searching/:algorithm',
  LINKED_LIST: '/algorithms/linked-list',
  LINKED_LIST_ALGO: '/algorithms/linked-list/:type/:operation',
  STACK: '/algorithms/stack',
  STACK_ALGO: '/algorithms/stack/:operation',
  QUEUE: '/algorithms/queue',
  QUEUE_ALGO: '/algorithms/queue/:type/:operation',
  TREES: '/algorithms/trees',
  TREE_ALGO: '/algorithms/trees/:algorithm',
  GRAPH: '/algorithms/graph',
  GRAPH_ALGO: '/algorithms/graph/:algorithm',
  PATHFINDING: '/algorithms/pathfinding',
  PATHFINDING_ALGO: '/algorithms/pathfinding/:algorithm',
  DP: '/algorithms/dynamic-programming',
  DP_ALGO: '/algorithms/dynamic-programming/:algorithm',
  GREEDY: '/algorithms/greedy',
  GREEDY_ALGO: '/algorithms/greedy/:algorithm',
  BACKTRACKING: '/algorithms/backtracking',
  BACKTRACKING_ALGO: '/algorithms/backtracking/:algorithm',
  COMPARISON: '/compare',
  BENCHMARK: '/benchmark',
  QUIZ: '/quiz',
  PRACTICE: '/practice',
  ACHIEVEMENTS: '/achievements',
  SETTINGS: '/settings',
  NOT_FOUND: '*',
};

export const NAV_ITEMS = [
  {
    label: 'Dashboard',
    path: ROUTES.DASHBOARD,
    icon: 'LayoutDashboard',
  },
  {
    label: 'Algorithms',
    icon: 'Binary',
    children: [
      { label: 'Sorting', path: ROUTES.SORTING, icon: 'ArrowUpDown' },
      { label: 'Searching', path: ROUTES.SEARCHING, icon: 'Search' },
      { label: 'Linked List', path: ROUTES.LINKED_LIST, icon: 'Link' },
      { label: 'Stack', path: ROUTES.STACK, icon: 'Layers' },
      { label: 'Queue', path: ROUTES.QUEUE, icon: 'ListOrdered' },
      { label: 'Trees', path: ROUTES.TREES, icon: 'GitBranch' },
      { label: 'Graph', path: ROUTES.GRAPH, icon: 'Share2' },
      { label: 'Pathfinding', path: ROUTES.PATHFINDING, icon: 'Map' },
      { label: 'Dynamic Programming', path: ROUTES.DP, icon: 'Grid3x3' },
      { label: 'Greedy', path: ROUTES.GREEDY, icon: 'Target' },
      { label: 'Backtracking', path: ROUTES.BACKTRACKING, icon: 'Undo2' },
    ],
  },
  {
    label: 'Compare',
    path: ROUTES.COMPARISON,
    icon: 'GitCompare',
  },
  {
    label: 'Benchmark',
    path: ROUTES.BENCHMARK,
    icon: 'BarChart3',
  },
  {
    label: 'Quiz',
    path: ROUTES.QUIZ,
    icon: 'HelpCircle',
  },
  {
    label: 'Practice',
    path: ROUTES.PRACTICE,
    icon: 'Code2',
  },
  {
    label: 'Achievements',
    path: ROUTES.ACHIEVEMENTS,
    icon: 'Trophy',
  },
];
